### ISSUE TITLE
Default `confirmQuit` to true?

### ISSUE THREAD

**Issue by karlhorky** [zachflower/hyper-confirm#3]
Hey there, thanks for the plugin, this is great!

Would you consider defaulting the `confirmQuit` setting to `true`? So that the plugin works out of the box?

**Comment by zachflower** [comment]
Yeah, that's a good idea. It's a pretty trivial change, but will mean a major version bump since it's not (technically) backwards compatible. I'll see if I can get an update out in the next week or so.

**Comment by zachflower** [comment]
Only 2 years late on this commit! v1.0.0 now enables `hyper-confirm` by default (and can be disabled by setting `confirmQuit` to `false`)

**Comment by karlhorky** [comment]
Nice one Zach, cheers!
