### ISSUE TITLE
Doesn’t seem to work with Hyper 2

### ISSUE THREAD

**Issue by mischah** [zachflower/hyper-confirm#4]
Hej @zachflower,

thanks for that awesome plugin. 

Did I configure it wrong, or doesn’t it work with Hyper 2?

![image](https://user-images.githubusercontent.com/441011/38895927-a72e9a72-4291-11e8-8ded-46c97994a819.png)

Edit: I’m on Mac OS 10.12.6 btw.

**Comment by ultraN** [comment]
Confirm that it isn't working under Hyper 2.0.0

**Comment by zachflower** [comment]
Validated this on my end. It seems that the Electron `before-quit` event in Hyper v2.0.0 is executed _after_ all windows are closed, rather than before (which was the v1.* behavior).

**Comment by tvanalstyne** [comment]
Just curious if you've had any luck getting this working in Hyper 2.0.0? Thanks so much!

**Comment by mserajnik** [comment]
Did this fix itself? Because it works fine for me on macOS 10.13.6.

<img width="420" alt="screen shot 2018-08-14 at 13 58 45" src="https://user-images.githubusercontent.com/28833155/44090387-48cbd382-9fca-11e8-9de0-bf6a0952a847.png">

**Comment by travVT** [comment]
I think this might have been a Windows issue. Thanks!
