### ISSUE TITLE
Doesn't work on Windows on Hyper 3

### ISSUE THREAD

**Issue by roshinv** [zachflower/hyper-confirm#6]
I use Windows and Hyper 3 and I get no confirmation message whatsoever. Can you please update this?

**Comment by zachflower** [comment]
Hi @roshinv, thanks for the report! I'm just getting back into using Hyper as my primary terminal emulator, so I should have some improvements coming down the pike in the next few weeks. That said, please feel free to open up a pull request with any bug fixes as well!

**Comment by zachflower** [comment]
Hi @roshinv I just published an update that should work for Windows users that will pop a confirmation dialog whenever you close a window (if `confirmQuit` is set to `true` in the `.hyper.js` config).
