### ISSUE TITLE
Not working on Hyper 3.0.2 (stable)

### ISSUE THREAD

**Issue by g3rhard** [zachflower/hyper-confirm#8]
Hello there, it seems like a plugin won't work on Hyper 3.0.2:
```
Renderers: WebGL (5)
Plugins: 
  hyper-material-theme (3.0.1),
  hyperlinks (0.5.0),
  hyper-statusline (1.7.6),
  hyper-confirm (0.2.0)

Created by Guillermo Rauch
Copyright © 2019 ZEIT, Inc.
```

In .hyper.js
```
    confirmQuit: true,
...
  plugins: ["hyper-material-theme", "hyperlinks", "hyper-statusline", "hyper-confirm"],
```

**Comment by zachflower** [comment]
Hi @g3rhard, apologies, I've let this project get a little stale but am in the process of picking it back up and dusting it off. I've just re-installed Hyper v3.0.2 and am unable to reproduce your problem. Can you confirm your operating system, and would you mind posting your full `.hyper.hs` config?

**Comment by g3rhard** [comment]
@zachflower Here is my Hyper config: https://gist.github.com/g3rhard/f6c3ae5928338401b8e1467acc3019a5. 

Just today I installed Hyper again from brew:
```
❯ brew cask install hyper

```

I use macOS Catalina 10.15.6

**Comment by smebberson** [comment]
I can also confirm this is not working. I'm on macOS Catalina 10.15.7 with Hyper 3.0.2.

**Comment by g3rhard** [comment]
Closed, as didn't have a chance to use Hyper everyday and this plugin is not working with the latest version of Hyper - app is not opening after installing plugin.
